### ISSUE TITLE
Doesnt work

### ISSUE THREAD

**Issue by dimagoltsman** [kamushadenes/tracker17#3]
it fails on any package

**Comment by Tukks** [comment]
17Track changed his private api.

**Comment by dimagoltsman** [comment]
hey, just checked and it works.
this workflow doesnt use api. it uses headless chrome (you need to have chrome installed)
![image](https://user-images.githubusercontent.com/1561226/80289554-cb369080-8747-11ea-9260-cb69ac6b6e9c.png)
